# Base on https://github.com/jdaarevalo/docker_postgres_with_data

version: '3.7'
services:
    dvdrental:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5445:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./dvdrental:/docker-entrypoint-initdb.d